/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batepapo;


import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Miklécio
 */
public class ClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteFrame
     */
    private static String host = "127.0.0.3";
    private Socket s;
    private String historico="";
    public static char b='0';
    private String[] lista1;
    DefaultListModel<String> lista2 = new DefaultListModel<>();
    //String[] lista =new String[20];
    public ClienteFrame() throws IOException, ClassNotFoundException {
        initComponents();
        cliente();
        //Thread que atualiza as entradas
        new Thread(new Runnable() {
            @Override
            public void run() {
                
                while(true){
                    String leitura="";
                    InputStream con;
                    try {
                        con = s.getInputStream();
                        // colocar o inputstream no formato de objeto
                        ObjectInputStream entrada = new ObjectInputStream(con);
                        leitura=entrada.readObject().toString();
                        if(leitura.contains("#Requered")){
                            lista1=leitura.split("#");
                            lista2.clear();
                            for(int i=2;i<lista1.length;i++){
                                lista2.add(i-2,lista1[i]);
                            }
                            listagemCli.setModel(lista2);
                        }
                        else{
                            historico+=leitura+"\n";
                        }
                    } catch (IOException | ClassNotFoundException ex) {
                        Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                painel2.setText(historico);
                
                
                /*if(b=='1'){
                    //atualiza a cada 3 segundos com os clientes conectados
                    ObjectOutputStream requisitar;
                    try {
                        
                        Thread.sleep(4000);
                        requisitar = new ObjectOutputStream(s.getOutputStream());
                        requisitar.writeObject("#RequeredClient");
                        requisitar.flush();
                    } catch (IOException ex) {
                        Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }   catch (InterruptedException ex) {
                            Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    
                }*/
                
               }
                
            }
        }).start();
        
    }
    
    private void cliente() throws IOException{
        
        painel1.setVisible(false);
        s=new Socket(host, 1234);
        
        
        if (s.isConnected()) {
            //adiciona os clientes a lista de clientes conectados
            
            /*for(int i=0;i<=3;i++){
                lista2.addElement("Cliente "+i);
            }
          listagemCli.setModel(lista2);*/
        }
        else {
            System.out.println("Erro na conexão!");
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painel1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listagemCli = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        painel2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(painel1);

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listagemCli.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listagemCliValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listagemCli);

        jScrollPane3.setViewportView(painel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String msg;
        ObjectOutputStream saida;
        try {
            saida = new ObjectOutputStream(s.getOutputStream());
            msg=painel1.getText();
            saida.writeObject(msg);
            saida.flush();
            historico+="Eu:"+msg+"\n";
            painel1.setText("");
            painel2.setText(historico);
        } catch (IOException ex) {
            Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listagemCliValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listagemCliValueChanged
        ObjectOutputStream saidaTroca;
        if(b=='0'){
        try {
            listagemCli.getSelectedIndex();
            saidaTroca = new ObjectOutputStream(s.getOutputStream());
            saidaTroca.writeObject(listagemCli.getSelectedIndex());
            saidaTroca.flush();
        } catch (IOException ex) {
            Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        listagemCli.setEnabled(false);
        painel1.setVisible(true);
        b='1';
        //System.out.println(b);
        }
    }//GEN-LAST:event_listagemCliValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClienteFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listagemCli;
    private javax.swing.JTextPane painel1;
    private javax.swing.JTextPane painel2;
    // End of variables declaration//GEN-END:variables
}
